/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: '#0058bc',
        'primary-container': '#0070eb',
        'on-primary': '#ffffff',
        'on-primary-container': '#fefcff',
        'primary-fixed': '#d8e2ff',
        'primary-fixed-dim': '#adc6ff',
        'inverse-primary': '#adc6ff',
        secondary: '#5d5e63',
        'secondary-container': '#e0dfe4',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#626267',
        'secondary-fixed': '#e3e2e7',
        'secondary-fixed-dim': '#c6c6cb',
        tertiary: '#9e3d00',
        'tertiary-container': '#c64f00',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#fffbff',
        'tertiary-fixed': '#ffdbcc',
        'tertiary-fixed-dim': '#ffb595',
        surface: '#f9f9fe',
        'surface-bright': '#f9f9fe',
        'surface-dim': '#d9dade',
        'surface-variant': '#e2e2e7',
        'surface-container': '#ededf2',
        'surface-container-low': '#f3f3f8',
        'surface-container-high': '#e8e8ed',
        'surface-container-highest': '#e2e2e7',
        'surface-container-lowest': '#ffffff',
        'surface-tint': '#005bc1',
        'on-surface': '#1a1c1f',
        'on-surface-variant': '#414755',
        'on-background': '#1a1c1f',
        background: '#f9f9fe',
        outline: '#717786',
        'outline-variant': '#c1c6d7',
        'inverse-surface': '#2e3034',
        'inverse-on-surface': '#f0f0f5',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
      },
      borderRadius: {
        DEFAULT: '1rem',
        sm: '0.5rem',
        md: '1.5rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
      fontFamily: {
        sans: ['Inter', 'PingFang SC', 'Noto Sans SC', 'Microsoft YaHei', 'sans-serif'],
      },
      boxShadow: {
        glass: '0 8px 32px 0 rgba(31, 38, 135, 0.07)',
        'glass-lg': '0 20px 40px -10px rgba(26, 28, 31, 0.06)',
        float: '0 12px 24px rgba(0, 88, 188, 0.3)',
      },
    },
  },
  plugins: [],
}
